name=input("What is your name?")
age=input("What is your age?")
university=input("What university do you attend?")
course=input("What course are you taking?")
hobby=input("What is your favorite hobby?")
colour=input("What is your favorite colour?")
food=input("What is your favorite food?")
print(f"Your name is {name}")
print(f"You are {age} years old")
print(f"You attend {university}")
print(f"Your course is {course}")
print(f"Your favorite hobby is {hobby}")
print(f"Your favorite colour is {colour}")
print(f"Your favorite food is {food}")